services:
  app:
    build: .docker/app
    stdin_open: true
    tty: true
    container_name: app.proiect_vue_2025
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
      - "5173:5173"
      - "4173:4173" 
    volumes:
      - .:/app
      # exclude
      - /app/.git/
      - /app/api/
    working_dir: /app
    user: 1000:1000
  api:
    build: .docker/api
    stdin_open: true
    tty: true
    container_name: api.proiect_vue_2025
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
      # exclude
      - /api/.git/
    working_dir: /api
    user: 1000:1000 
  
  mysql:
    image: mysql:8.0.40
    container_name: mysql.proiect_vue_2025
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: proiect_vue_2025
      MYSQL_USER: proiect_vue_2025
      MYSQL_PASSWORD: proiect_vue_2025
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./database:/database:rw
    restart: always
  ws:
    build: .docker/ws
    stdin_open: true
    tty: true
    container_name: ws.proiect_vue_2025
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
      - "3001:3001"
    volumes:
      - ./ws:/ws
      # exclude
      - /ws/.git/
    working_dir: /ws
    user: 1000:1000
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: pma.proiect_vue_2025
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mysql.proiect_vue_2025
      PMA_USER: proiect_vue_2025
      PMA_PASSWORD: proiect_vue_2025
      UPLOAD_LIMIT: 250M
    # networks:
    #   - default
    restart: always

volumes:
  mysql_data:
    driver: local